name: Build Noer OS

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies for building ISO
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo -E apt-get update
        sudo -E apt-get install -y debootstrap squashfs-tools grub-pc-bin grub-efi-amd64-bin mtools xorriso dosfstools

    - name: Run Build Script
      run: |
        sudo bash scripts/build.sh

    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NoerOS-Live
        path: NoerOS.iso
        retention-days: 7
